### ISSUE TITLE
Slurm Install path Issues. Ubuntu 18.04

### ISSUE THREAD

**Issue by dooglz** [PySlurm/pyslurm#120]
#### Details

* Slurm Version: 17.11.0.3
* Python Version: Python 2.7.15rc1
* Cython Version:  0.26.1
* PySlurm Branch: 17.11.0
* Linux Distribution: Ubuntu 18.04 - from Ubuntu:bionic docker image

#### Issue
After installing Slurm from the Ubuntu Apt repo  (slurm-client & libslurm-dev)
https://packages.ubuntu.com/hu/bionic/amd64/slurm-client/filelist
https://packages.ubuntu.com/hu/bionic/amd64/libslurm-dev/filelist

the slurm.h is in:
/usr/include/**slurm-wlm**/slurm.h
and libslurm.so
/usr/lib/**x86_64-linux-gnu**/libslurm.so

Using 
`python setup.py build --slurm-inc=/usr/include/slurm-wlm --slurm-lib=/usr/lib/x86_64-linux-gnu/

Does not work due to:
https://github.com/PySlurm/pyslurm/blob/17.11.0/setup.py#L257

As code appends "/slurm/" to the --slurm-inc argument, and 'lib64' or 'lib' to --slurm-lib
This is also a problem in pyslurm/pyslurm.c:498
Which means it ends up looking here:
/usr/include/slurm-wlm/**_slurm_**/slurm.h

#### Potential Solution: 
Change script behaviour to try input arguments verbatim if adding additional suffix paths don't work

#### workaround: 
place symlinks to redirect the script to look in the right place
```
ln -sf /usr/include/slurm-wlm/ /usr/include/slurm
mkdir /usr/lib/slurm
ln -sf /usr/lib/x86_64-linux-gnu /usr/lib/slurm/lib
python setup.py build  --slurm-inc=/usr/include/ --slurm-lib=/usr/lib/slurm
```

**Comment by giovtorres** [comment]
Typically, slurm headers are installed into `/PATH/slurm/slurm.h`, inside a `slurm/` subdirectory.  Let me try to modify the search in `setup.py` such that it will look for `slurm.h` without prepending `slurm/` in front of it.

**Comment by giovtorres** [comment]
I merged that branch.  Give it a try now.

**Comment by marksantcroos** [comment]
This doesn't solve the problem that pyslurm.c also has an `#include "slurm/spank.h"`, does it?

**Comment by marksantcroos** [comment]
I've opened a ticket upstream too: https://bugs.schedmd.com/show_bug.cgi?id=6827.

**Comment by giovtorres** [comment]
Looks like PySlurm checks for the slurm header in paths with and without `slurm/` prepended, and I didn't do the same for the shared library.  I'll go ahead and update this.

**Comment by giovtorres** [comment]
@marksantcroos @dooglz The build step should find the library and header now, even using Ubuntu slurm packages.
